/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package final_project;

import com.itextpdf.text.*;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import java.awt.Color;
import java.io.File;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Properties;
import java.util.Vector;
import javax.activation.DataHandler;
import javax.activation.DataSource;
import javax.activation.FileDataSource;
import javax.mail.Message;
import javax.mail.Multipart;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeBodyPart;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.MimeMultipart;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import net.sf.dynamicreports.jasper.builder.JasperReportBuilder;
import net.sf.dynamicreports.report.builder.DynamicReports;
import net.sf.dynamicreports.report.builder.column.Columns;
import net.sf.dynamicreports.report.builder.column.TextColumnBuilder;
import net.sf.dynamicreports.report.builder.component.FillerBuilder;
import net.sf.dynamicreports.report.builder.component.ImageBuilder;
import net.sf.dynamicreports.report.builder.style.StyleBuilder;
import net.sf.dynamicreports.report.constant.HorizontalAlignment;
//import javax.swing.text.Element;

/**
 *
 * @author DILSHAN
 */
public class Bill extends javax.swing.JFrame {

    /**
     * Creates new form Bill
     */
    int xMouse;
    int yMouse;

    public Bill(String orderString) {
        initComponents();
        this.setLocationRelativeTo(null);
        jTextField1.setText(orderString);
        searchByOno();

    }

    public Bill() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Order No :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 79, 31));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Customer Name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 140, 31));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Payment Total :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 130, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Payed Amount :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Due Payment");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jTextField1.setToolTipText("Order No.");
        jTextField1.setNextFocusableComponent(jTextField4);
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 220, 31));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 220, 30));

        jTextField2.setEditable(false);
        jTextField2.setToolTipText("Name of the Customer");
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 220, 31));

        jTextField3.setEditable(false);
        jTextField3.setToolTipText("Total Payment for the order");
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 220, 31));

        jTextField4.setEditable(false);
        jTextField4.setToolTipText("Payed amount");
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 100, 31));

        jTextField5.setEditable(false);
        jTextField5.setToolTipText("Payment Due. for the current order");
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 160, 31));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/pay.png"))); // NOI18N
        jButton2.setText("Pay");
        jButton2.setToolTipText("Make Payment");
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, -1, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/clear1.png"))); // NOI18N
        jButton3.setText("Clear");
        jButton3.setToolTipText("Clear fields");
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, -1, -1));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/generate.png"))); // NOI18N
        jButton5.setText("Generate");
        jButton5.setToolTipText("Generate the Invoice for current order");
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Email-icon32.png"))); // NOI18N
        jButton4.setText("mail");
        jButton4.setToolTipText("Send order completion e-Mail to the customer ");
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Status :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("+");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 195, -1, -1));

        jTextField7.setToolTipText("Paying amount");
        jTextField7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField7KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 100, 30));

        jTextField6.setEditable(false);
        jTextField6.setToolTipText("Status of the order");
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 160, 31));

        jButton1.setText("jButton1");
        jButton1.setToolTipText("Updates the status of the order");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 20, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Actions-button-cancel-icon (1).png"))); // NOI18N
        jLabel8.setToolTipText("Close");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 30, -1));

        jLabel9.setFont(new java.awt.Font("Tekton Pro Cond", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("                                                                         Bill");
        jLabel9.setToolTipText("Close window");
        jLabel9.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel9MouseDragged(evt);
            }
        });
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel9MousePressed(evt);
            }
        });
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 410, 20));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BACKIMG/bill.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        cls();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        try {
            Statement st = javaConnect.ConnectorDB();
            ResultSet r = st.executeQuery("SELECT DISTINCT order_no FROM order_items WHERE order_no LIKE '%" + jTextField1.getText() + "%'");
            Vector v1 = new Vector();

            while (r.next()) {
                v1.add(r.getString("order_no"));

            }

            jComboBox1.setModel(new DefaultComboBoxModel(v1));
            jComboBox1.setPopupVisible(true);
            jTextField1.setText(jTextField1.getText());

        } catch (Exception e) {

        }
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        jTextField1.setText(jComboBox1.getSelectedItem().toString());
        searchByOno();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            cal();
            Statement st = javaConnect.ConnectorDB();
            st.executeUpdate("update order_payments set advance='" + s4 + "',payment_date ='" + today + "' where order_no='" + s1 + "'");

        } catch (Exception e) {

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            Statement st=javaConnect.ConnectorDB();
            ResultSet rs=st.executeQuery("SELECT * FROM order_items where order_no='"+jTextField1.getText()+"'");
            JasperReportBuilder report = DynamicReports.report();
            
            //Styles
            StyleBuilder boldStyle=DynamicReports.stl.style().bold();
            StyleBuilder titleStyle=DynamicReports.stl.style(boldStyle).setHorizontalAlignment(HorizontalAlignment.CENTER).setFontSize(15);
            StyleBuilder TableHeaderStyle=DynamicReports.stl.style(titleStyle).setBorder(
            
            DynamicReports.stl.pen1Point()
            ).setBackgroundColor(Color.LIGHT_GRAY);
            StyleBuilder boldRight=DynamicReports.stl.style(boldStyle).setHorizontalAlignment(HorizontalAlignment.RIGHT).setFontSize(15);
            StyleBuilder boldLeft=DynamicReports.stl.style(boldStyle).setHorizontalAlignment(HorizontalAlignment.LEFT).setFontSize(15);
             StyleBuilder boldCenter=DynamicReports.stl.style(boldStyle).setHorizontalAlignment(HorizontalAlignment.CENTER).setFontSize(15);
            
             StyleBuilder normalRight=DynamicReports.stl.style().setHorizontalAlignment(HorizontalAlignment.RIGHT).setFontSize(13);
            StyleBuilder normalLeft=DynamicReports.stl.style().setHorizontalAlignment(HorizontalAlignment.LEFT).setFontSize(13);


//Add image
            InputStream stream =Bill.class.getResourceAsStream("/IMG/InvoiceHeader.png");
            ImageBuilder img=DynamicReports.cmp.image(stream).setFixedDimension(570, 260)
                    .setStyle(DynamicReports.stl.style().setHorizontalAlignment(HorizontalAlignment.CENTER));
            
            
            //title
            net.sf.dynamicreports.report.builder.component.TextFieldBuilder<String> title = DynamicReports.cmp.text("Swarna Graphics");
            title.setStyle(titleStyle);
            
            report.title(DynamicReports.cmp.horizontalFlowList(img));
            //report.title(title);

            //add table
            //add columns
            Date d=new Date();
            String dtto=dt.format(d);
            report.title(DynamicReports.cmp.horizontalFlowList(DynamicReports.cmp.text("To : "+jTextField2.getText()).setStyle(boldLeft),DynamicReports.cmp.text("Invoice No : "+jTextField1.getText()).setStyle(boldCenter),DynamicReports.cmp.text("Date : "+dtto).setStyle(boldRight) ));
           report.title(DynamicReports.cmp.text("\n "));
            TextColumnBuilder<String> itemNameColumn=Columns.column("Item", "type",DynamicReports.type.stringType());
            TextColumnBuilder<String> itemQty=Columns.column("QTY", "size",DynamicReports.type.stringType());
            TextColumnBuilder<Integer> itemPrice=Columns.column("Price", "item_price",DynamicReports.type.integerType());
            
            TextColumnBuilder<Integer> rownumCol=Columns.reportRowNumberColumn("  No  ").setFixedColumns(5).setHorizontalAlignment(HorizontalAlignment.CENTER);
            
            
          //  report.subtotalsAtSummary(DynamicReports.sbt.sum(itemPrice));
            
            report.columns(rownumCol,itemNameColumn,itemQty,itemPrice);
            
            
            
            report.setColumnTitleStyle(TableHeaderStyle);
            report.setDataSource(rs);
            
            FillerBuilder filler=DynamicReports.cmp.filler().setStyle(DynamicReports.stl.style().setBorder(
            DynamicReports.stl.pen2Point())).setFixedHeight(2);
            
          
            report.highlightDetailEvenRows();
            
            report.summary(DynamicReports.cmp.text("\n "));
            String rep="Total : "+jTextField3.getText()+"\nPayed : ("+jTextField4.getText()+")\nDue Payment : "+jTextField5.getText()+"\n";
            
            report.summary(DynamicReports.cmp.text(rep).setStyle(boldRight));
            
            report.summary(DynamicReports.cmp.text("\n "));
            report.summary(DynamicReports.cmp.text("\n "));
            report.summary(DynamicReports.cmp.text("\n "));
            String abc="(Customer)";
            String xyz="(Cashier)";
            report.summary(DynamicReports.cmp.horizontalFlowList(DynamicReports.cmp.text(abc).setStyle(normalLeft),DynamicReports.cmp.text(xyz).setStyle(normalRight) ));
            
           report.show(false);
            
            report.toPdf(new FileOutputStream(new File("c:\\temp\\Invoice.pdf")));

        } catch (Exception e) {
            e.printStackTrace();
        }

//        try {
//            Document document = new Document();
//            PdfWriter.getInstance(document, new FileOutputStream(FILE));
//            document.open();
//            addMetaData(document);
//            addTitlePage(document);
//            //addContent(document);
//            document.close();
//
//            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + "C:\\temp\\Bill.pdf");
//
//        } catch (Exception e) {
//            e.printStackTrace();
//        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jLabel9MousePressed

    private void jLabel9MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jLabel9MouseDragged

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        if (emailadd.equals("")) {
            JOptionPane.showMessageDialog(null, "Customer dosen't have any e-Mail address ");
        } else {

            sendMail();
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        char c = evt.getKeyChar();

        if (Character.isDigit(c)) {
        } else {

            evt.consume();

        }
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7KeyTyped
        char c = evt.getKeyChar();

        if (Character.isDigit(c)) {
        } else {

            evt.consume();

        }
    }//GEN-LAST:event_jTextField7KeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        if (jTextField1.getText().equals("")) {
            Status sssss = new Status();
            sssss.setVisible(true);
        } else {
            Status sssss = new Status(jTextField1.getText());
            sssss.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bill().setVisible(true);
            }
        });
    }

    private void addTitlePage(Document document)
            throws DocumentException {

        Anchor anchor = new Anchor();
//anchor.setName("");

        Chapter catPart = new Chapter(new Paragraph(anchor), 1);
        Paragraph preface = new Paragraph();
// We add one empty line
        addEmptyLine(preface, 1);
// Lets write a big header
        preface.add(new Paragraph("Invoice", catFont));
        // addEmptyLine(preface, 1);
        //preface.setAlignment((Element.ALIGN_CENTER);

        preface.add(new Paragraph("Swarna Graphics", catFont));
        addEmptyLine(preface, 1);

        preface.add(new Paragraph("Order No: " + s1));
        preface.add(new Paragraph("Customer: " + s2));
        preface.add(new Paragraph("Order Date: " + odate));
        Date dx = new Date();
        String dy = dt.format(dx);

        preface.add(new Paragraph("Invoice issued on: " + dy));
        addEmptyLine(preface, 2);

// Second parameter is the number of the chapter
        Section subCatPart = catPart.addSection(preface);

        createTable(subCatPart);
        Paragraph preface2 = new Paragraph();
        addEmptyLine(preface2, 1);
        preface2.add(new Paragraph("Total                :   " + totbill));
        preface2.add(new Paragraph("Payments        :  (" + adv + ")"));
        preface2.add(new Paragraph("Payments Due :   " + du));

        document.add(catPart);

        document.add(preface2);

    }

    public void sendMail() {
        Properties props = new Properties();
        props.put("mail.smtp.host", "smtp.gmail.com");
        props.put("mail.smtp.socketFactory.port", "465");
        props.put("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.port", "465");

        Session session = Session.getDefaultInstance(props,
                new javax.mail.Authenticator() {
                    protected PasswordAuthentication getPasswordAuthentication() {
                        return new PasswordAuthentication("contact.swarna.graphics@gmail.com", "sgprint@1");
                    }
                }
        );
        try {
            String msgBody="Hi " + s2 + ", \nYour order with order no: " + s1 + " is finished. you can collect it now from our office \nDue payment for the order is :LKR " + s5 + "/= \n\nWith regards, \nSwarna Graphics ";
            
            Message message = new MimeMessage(session);
            message.setFrom(new InternetAddress("contact.swarna.graphics@gmail.com"));
            message.setRecipients(Message.RecipientType.TO, InternetAddress.parse(emailadd));
            message.setSubject("Order Completed");
            
            
            MimeBodyPart messageBodyPart=new MimeBodyPart();
            messageBodyPart.setText(msgBody);
            Multipart multipart=new MimeMultipart();
            multipart.addBodyPart(messageBodyPart);
            
            
            messageBodyPart=new MimeBodyPart();
            DataSource source=new FileDataSource("c:\\temp\\Invoice.pdf");
            messageBodyPart.setDataHandler(new DataHandler(source));
            messageBodyPart.setFileName("Invoice.pdf");
            multipart.addBodyPart(messageBodyPart);
            message.setContent(multipart);
            
            Transport.send(message);
            JOptionPane.showMessageDialog(null, "sent");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private static void addMetaData(Document document) {
        document.addTitle("INOICE");
        document.addSubject("INOICE");
        document.addKeywords("Bill, Invoice");
        document.addAuthor("Swarna Graphics");
        document.addCreator("Swarna Graphics");
    }

    private void createTable(Section subCatPart)
            throws BadElementException {

        PdfPTable table = new PdfPTable(3);
// t.setBorderColor(BaseColor.GRAY);
// t.setPadding(4);
// t.setSpacing(4);
// t.setBorderWidth(1);

        PdfPCell c1 = new PdfPCell(new Phrase("Item"));
        //  c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);
        c1 = new PdfPCell(new Phrase("QTY"));
        //c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);

        c1 = new PdfPCell(new Phrase("Item Price"));
        // c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);

        table.setHeaderRows(1);

        try {
            Statement st = javaConnect.ConnectorDB();
            ResultSet rs = st.executeQuery("select * from order_items where order_no='" + s1 + "' ");
            String a, c = null;
            String b = null;
            while (rs.next()) {
                a = rs.getString("type");
                b = rs.getString("size");
                c = rs.getString("item_price");

                table.addCell(a);
                table.addCell(b);
                table.addCell(c);

            }
            table.addCell("Total");
            table.addCell(b);
            rs = st.executeQuery("select * from order_payments where order_no='" + s1 + "' ");
            if (rs.next()) {
                System.out.println("KKKKKKKKKKKKKKKKKKK");
                totbill = rs.getString("total");

                adv = rs.getString("advance");

                int x = Integer.parseInt(totbill);
                int y = Integer.parseInt(adv);
                int duue = x - y;
                du = Integer.toString(duue);

                table.addCell(totbill);

            }

        } catch (Exception e) {

        }

        subCatPart.add(table);

    }

    private static void createList(Section subCatPart) {
        List list = new List(true, false, 10);
        list.add(new ListItem("First point"));
        list.add(new ListItem("Second point"));
        list.add(new ListItem("Third point"));
        subCatPart.add(list);
    }

    private static void addEmptyLine(Paragraph paragraph, int number) {
        for (int i = 0; i < number; i++) {
            paragraph.add(new Paragraph(" "));
        }
    }

    public void cal() {
        int newpay = 0;
        s7 = jTextField7.getText();
        s3 = jTextField3.getText();
        s4 = jTextField4.getText();

        newpay = Integer.parseInt(s7);
        tot = Integer.parseInt(s3);
        payed = Integer.parseInt(s4);
        payed = payed + newpay;

        due = tot - payed;

        s5 = Integer.toString(due);
        s4 = Integer.toString(payed);
        jTextField5.setText(s5);
        jTextField4.setText(s4);
        Date d = new Date();
        today = dt.format(d);
        jTextField7.setText("");
    }

    public void cls() {
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jButton4.setEnabled(true);
    }

    public void searchByOno() {
        try {
            s1 = jTextField1.getText();
            Statement st = javaConnect.ConnectorDB();
            String sql1 = "select * from order_ref where order_no='" + s1 + "' ";
            String sql2 = "select * from order_payments where order_no='" + s1 + "' ";
            String sql3 = "select * from order_status where order_no='" + s1 + "' ";

            ResultSet rs;

            rs = st.executeQuery(sql1);
            if (rs.next()) {

                custno = rs.getString("cust_nic");
                odate = rs.getString("o_date");

            }
            rs = st.executeQuery(sql2);
            if (rs.next()) {

                s3 = rs.getString("total");
                s4 = rs.getString("advance");
                pday = rs.getString("payment_date");
            }

            tot = Integer.parseInt(s3);
            if (s4.equals("")) {
                payed = 0;
                s4 = "0";
            } else {
                payed = Integer.parseInt(s4);
            }
            due = tot - payed;
            s5 = Integer.toString(due);

            rs = st.executeQuery(sql3);
            if (rs.next()) {

                s6 = rs.getString("status");

            }
            String sql4 = "select * from customer where NIC='" + custno + "' ";
            rs = st.executeQuery(sql4);

            if (rs.next()) {

                s2 = rs.getString("Name");
                emailadd = rs.getString("Email");

            }
            if (emailadd.equals("")) {

                jButton4.setEnabled(false);
            } else {
                jButton4.setEnabled(true);
            }

        } catch (Exception e) {
            //cls();
        }

        jTextField2.setText(s2);
        jTextField3.setText(s3);
        jTextField4.setText(s4);
        jTextField5.setText(s5);
        jTextField6.setText(s6);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables

    String s1, s2, s3, s4, s5, s6, s7, emailadd, custno = "";
    String odate, fdate, pday, today = null;
    int tot, payed, due = 0;
    DateFormat dt = new SimpleDateFormat("yyyy-MM-dd");
    private static String FILE = "c:/temp/Bill.pdf";
    private static Font catFont = new Font(Font.FontFamily.TIMES_ROMAN, 18, Font.BOLD);
    private static Font redFont = new Font(Font.FontFamily.TIMES_ROMAN, 12, Font.NORMAL, BaseColor.RED);
    private static Font subFont = new Font(Font.FontFamily.TIMES_ROMAN, 16, Font.BOLD);
    private static Font smallBold = new Font(Font.FontFamily.TIMES_ROMAN, 12, Font.BOLD);
    String du, totbill, adv = null;
}
