/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package final_project;

/**
 *
 * @author DILSHAN
 */
public class Error extends javax.swing.JFrame {

    /**
     * Creates new form Error
     */
   
    public Error(String x) {
        
        
        initComponents();
        jmsg.setText(x);
        this.setVisible(true);
    }
    int xMouse;
    int yMouse;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jmsg = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jClose = new javax.swing.JLabel();
        jbar = new javax.swing.JLabel();
        jback = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jmsg.setFont(new java.awt.Font("Tekton Pro Ext", 3, 18)); // NOI18N
        jmsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jmsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 410, 120));

        jLabel3.setFont(new java.awt.Font("Nyala", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Error");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 190, 20));

        jButton1.setFont(new java.awt.Font("Nyala", 3, 24)); // NOI18N
        jButton1.setText("OK");
        jButton1.setBorderPainted(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 70, -1));

        jClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/close 3.png"))); // NOI18N
        jClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCloseMouseClicked(evt);
            }
        });
        getContentPane().add(jClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 2, -1, -1));

        jbar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BARIMG/510.png"))); // NOI18N
        jbar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jbarMouseDragged(evt);
            }
        });
        jbar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jbarMousePressed(evt);
            }
        });
        getContentPane().add(jbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 35));

        jback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BACKIMG/510x240.png"))); // NOI18N
        getContentPane().add(jback, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCloseMouseClicked
        this.dispose();
    }//GEN-LAST:event_jCloseMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbarMousePressed
             xMouse = evt.getX();
                yMouse = evt.getY();
       
    }//GEN-LAST:event_jbarMousePressed

    private void jbarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbarMouseDragged
                    int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jbarMouseDragged

    /**
     * @param args the command line arguments
     */

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jClose;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jback;
    private javax.swing.JLabel jbar;
    private javax.swing.JLabel jmsg;
    // End of variables declaration//GEN-END:variables
}
