/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package final_project;

import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hashen
 */
public class Order extends javax.swing.JFrame {

    int xMouse;
    int yMouse;

    /**
     * Creates new form Order
     */
    public Order() {
        initComponents();
        this.setLocationRelativeTo(null);
        try {
            getLostImage();
            noImg();
            jTextField2.setText("0");
            jTextField6.setText("0");
            //System.out.println("1 "+Arrays.toString(pib));
        } catch (Exception e) {

        }
    }

    public Order(String bb) {
        initComponents();
        this.setLocationRelativeTo(null);
        try {
            getLostImage();
            noImg();
            jTextField2.setText("0");
            jTextField6.setText("0");
            jTextField1.setText(bb);
            searchByOrder();
            //System.out.println("1 "+Arrays.toString(pib));
        } catch (Exception e) {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jComboBox4 = new javax.swing.JComboBox();
        jComboBox5 = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox();
        jTextField4 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jXDatePicker1 = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Actions-button-cancel-icon (1).png"))); // NOI18N
        jLabel2.setToolTipText("Close");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 0, 30, 30));

        jLabel3.setFont(new java.awt.Font("Tekton Pro Cond", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("                                                                                                                            Order");
        jLabel3.setToolTipText("Move window");
        jLabel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel3MouseDragged(evt);
            }
        });
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 4, 850, 20));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Order No");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 21, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Order Type");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 119, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Customer NIC");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 68, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Description");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 165, -1, -1));

        jTextField1.setToolTipText("Order No.");
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 21, 120, -1));

        jTextField3.setToolTipText("Current order's owner's NIC No.");
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField3KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField3KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 119, -1));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 120, -1));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 120, -1));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setToolTipText("Colours for the item");
        jScrollPane2.setViewportView(jTextArea2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, 152, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("No of Colours");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 280, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "T-shirt", "Baners", "Caps", "Other Cloths", "Flags", "Other" }));
        jComboBox1.setToolTipText("Select the Item Type");
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 119, 119, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        jComboBox2.setToolTipText("Select no of Colours for the item");
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 280, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Screen Type");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 318, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("QTY");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Price");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Finishing Date");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Colours");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, -1, -1));

        jTextField2.setEditable(false);
        jTextField2.setToolTipText("Total price of thhe entire order (auto generated)");
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, 87, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Stencil", "Tracing", "Positive" }));
        jComboBox3.setToolTipText("Choose the screen type");
        jPanel1.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 318, -1, -1));

        jTextField4.setEditable(false);
        jTextField4.setToolTipText("Item price (auto generated)");
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField4KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 81, -1));

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jTextArea3.setToolTipText("Extra details about the current item");
        jScrollPane3.setViewportView(jTextArea3);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 145, 158, -1));

        jXDatePicker1.setToolTipText("Select the finishing date for the order");
        jPanel1.add(jXDatePicker1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, 152, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Image", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 255, 0))); // NOI18N
        jPanel2.setOpaque(false);

        jLabel8.setToolTipText("Artwork/Image of the current item");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(631, 13, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/save 1.png"))); // NOI18N
        jButton2.setText("Add");
        jButton2.setToolTipText("Place current item to the order");
        jButton2.setContentAreaFilled(false);
        jButton2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/save 2.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(628, 301, -1, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/clear1.png"))); // NOI18N
        jButton3.setText("Remove");
        jButton3.setToolTipText("Delete the current item from the order");
        jButton3.setContentAreaFilled(false);
        jButton3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/clear2.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(743, 301, -1, -1));

        jTextField5.setToolTipText("Quantity");
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField5KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField5KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 81, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Total Payment");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Browse");
        jButton1.setToolTipText("Upload Artwork/Image");
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(711, 260, -1, -1));

        jButton8.setText("jButton8");
        jButton8.setToolTipText("Auto generates the next Order No.");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 20, -1));

        jButton9.setText("jButton9");
        jButton9.setToolTipText("Enter new customer Data");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 20, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Unit Price");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, -1));

        jTextField6.setText("0");
        jTextField6.setToolTipText("Enter the Unit Price");
        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField6KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField6KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 80, -1));

        jButton11.setText("jButton11");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 20, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 880, 370));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Items", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(204, 0, 0))); // NOI18N
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order", "Customer ", "Item No", "Type", "Description", "#Colours", "Colours", "Size", "Screen", "Price", "Order Date", "Finish Date"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 16, 858, 155));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/delete 1.png"))); // NOI18N
        jButton4.setText("Delete");
        jButton4.setToolTipText("Delete the entire order");
        jButton4.setContentAreaFilled(false);
        jButton4.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/delete 2.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 180, -1, -1));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/pay.png"))); // NOI18N
        jButton5.setText("Bill");
        jButton5.setToolTipText("Generate Bill, Pay , Send  Email to Customer");
        jButton5.setContentAreaFilled(false);
        jButton5.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/save 2.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/update a.png"))); // NOI18N
        jButton6.setText("Update Status");
        jButton6.setToolTipText("Update the processing status of the order");
        jButton6.setContentAreaFilled(false);
        jButton6.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/update 2.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, -1, -1));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/clear1.png"))); // NOI18N
        jButton7.setText("Clear");
        jButton7.setToolTipText("Clear Fields");
        jButton7.setContentAreaFilled(false);
        jButton7.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/clear2.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 180, -1, -1));

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/update a.png"))); // NOI18N
        jButton10.setText("Update Customer No");
        jButton10.setToolTipText("Updates the customer's ID No. in cases of mistakes");
        jButton10.setContentAreaFilled(false);
        jButton10.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/update 2.png"))); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 220, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 880, 230));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BACKIMG/order.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY(); // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MousePressed

    private void jLabel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);   // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseDragged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        filename = f.getAbsolutePath();

        try {
            File image = new File(filename);
            FileInputStream fis = new FileInputStream(image);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte[] buf = new byte[1024];

            for (int readNum; (readNum = fis.read(buf)) != -1;) {
                bos.write(buf, 0, readNum);
            }
            pib = bos.toByteArray();

            format = new ImageIcon(pib);
            jLabel8.setIcon(format);
        } catch (Exception e) {
            noImg();
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //cls();
        /*s2=jTextField2.getText();
         totOrder=Integer.parseInt(s2);
         s4=jTextField4.getText();
         ipval=Integer.parseInt(s4);
         totOrder=totOrder-ipval;
         s2=Integer.toString(totOrder);
         jTextField2.setText(s2);
         s1=jTextField1.getText();
         try{
         System.out.println("update error pay0");
         Statement stx=javaConnect.ConnectorDB();
         System.out.println("update error pay1");
         stx.executeQuery("update order_payments set total='"+s2+"' where order_no='"+s1+"' ");
         System.out.println("update error pay2");
         }catch(ClassNotFoundException | SQLException e){
         System.out.println("update error pay");
         }
        
         */

        try {
            s2 = jTextField2.getText();
            totOrder = Integer.parseInt(s2);
            totOrder = totOrder - Integer.parseInt(s4);
            s2 = Integer.toString(totOrder);
            jTextField2.setText(s2);
            Statement st = javaConnect.ConnectorDB();
            String sql = "update order_payments set total='" + s2 + "' where order_no='" + s1 + "' ";
            st.executeUpdate(sql);
        } catch (Exception e) {
        }

        delItem();
        delArt();
        clsSameOrder();
        searchByOrder();


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (jTextField1.getText().isEmpty() || jTextField1.getText().length() < 5) {
            JOptionPane.showMessageDialog(this, "Order No is Invalid");
        } else if (jTextField3.getText().isEmpty() || jTextField3.getText().length() != 10) {
            JOptionPane.showMessageDialog(this, "Customer NIC is Invalid");
        } else if (jTextArea3.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Description is Empty");
        } else if (jTextField6.getText().equals("0")) {
            JOptionPane.showMessageDialog(this, "Unit price can't be '0'");
        } else if (jTextField5.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Qty is Empty");
        } else if (jTextArea2.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Colours are Empty");
        } //        else  if (jTextField4.getText().isEmpty()) 
        //            JOptionPane.showMessageDialog(this, "Price is Empty");
        else {
            insert();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    void insert() {

        try {
            addItem();
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.setNumRows(0);

            try {
                String OrNo = jTextField1.getText();
                String a = "";

                Statement st = javaConnect.ConnectorDB();
                String sql1 = "select * from order_ref where order_no='" + OrNo + "' ";
                String sql2 = "select * from order_items where order_no='" + OrNo + "' ";
                //String sql3="select total from order_payments where order_no='"+OrNo+"' ";

                ResultSet rs = st.executeQuery(sql1);
                if (rs.next()) {
                    s3 = rs.getString("cust_nic");
                    ds2day = rs.getString("o_date");
                }
                rs = st.executeQuery(sql2);
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

                while (rs.next()) {
                    s1 = rs.getString("order_no");
                    a = rs.getString("item_no");
                    jcbs1 = rs.getString("type");
                    sa3 = rs.getString("desc");
                    jcbs2 = rs.getString("no_colours");
                    sa2 = rs.getString("colours");
                    s5 = rs.getString("size");
                    jcbs3 = rs.getString("screen");
                    s4 = rs.getString("item_price");
                    ds1 = rs.getString("finish_date");

                    Object[] row = {s1, s3, a, jcbs1, sa3, jcbs2, sa2, s5, jcbs3, s4, ds2day, ds1};
                    model.addRow(row);
                }

            } catch (Exception e) {
            }

        } catch (Exception e) {
        }
        clsSameOrder();
    }

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        try {
            ArrayList<String> data = new ArrayList<>();
            int row = jTable1.getSelectedRow();

            int col = model.getColumnCount();
            for (int i = 0; i < col; i++) {
                String x = model.getValueAt(row, i).toString();
                data.add(x);
            }
            s1 = data.get(0);
            s3 = data.get(1);
            String citem = data.get(2);
            cino = Integer.parseInt(citem);
            jcbs1 = data.get(3);
            sa3 = data.get(4);
            jcbs2 = data.get(5);
            sa2 = data.get(6);
            s5 = data.get(7);
            jcbs3 = data.get(8);
            s4 = data.get(9);
            String d = data.get(10);
            ds1 = data.get(11);

            Date y1 = dt.parse(d);
            Date y2 = dt.parse(ds1);

            jTextField3.setText(s3);
            jTextField5.setText(s5);
            jTextField4.setText(s4);

            jComboBox1.setSelectedItem(jcbs1);
            jComboBox2.setSelectedItem(jcbs3);
            jComboBox3.setSelectedItem(jcbs3);

            jTextArea2.setText(sa2);
            jTextArea3.setText(sa3);

            jXDatePicker1.setDate(y1);

            Statement st = javaConnect.ConnectorDB();
            ResultSet rs = st.executeQuery("select total from order_payments where order_no='" + s1 + "' ");
            if (rs.next()) {
                s2 = rs.getString("total");
                jTextField2.setText(s2);
            }
            System.out.println(citem);
            System.out.println(s1);
            ResultSet rs2 = st.executeQuery("select * from order_artwork where order_no='" + s1 + "' and item_no='" + citem + "' ");
            System.out.println("pic sql");
            if (rs2.next()) {
                System.out.println("pic1");
                pib = rs2.getBytes("img");
                System.out.println("pic2");
                format = new ImageIcon(pib);
                System.out.println("pic3");
                jLabel8.setIcon(format);
                System.out.println("pic4");

            }

        } catch (Exception e) {
            System.out.println("pic5");
        }


    }//GEN-LAST:event_jTable1MouseClicked

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        jTextField1.setText(jComboBox4.getSelectedItem().toString());
        searchByOrder();
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        try {
            Statement st = javaConnect.ConnectorDB();
            ResultSet r = st.executeQuery("SELECT order_no FROM order_ref WHERE order_no LIKE '%" + jTextField1.getText() + "%'");
            Vector v1 = new Vector();

            while (r.next()) {
                v1.add(r.getString("order_no"));

            }

            jComboBox4.setModel(new DefaultComboBoxModel(v1));
            jComboBox4.setPopupVisible(true);
            jTextField4.setText(jTextField1.getText());

        } catch (Exception e) {
            e.printStackTrace();

        }
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        jTextField3.setText(jComboBox5.getSelectedItem().toString());

    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jTextField3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyReleased
        try {
            Statement st = javaConnect.ConnectorDB();
            ResultSet r = st.executeQuery("SELECT NIC FROM customer WHERE NIC LIKE '%" + jTextField3.getText() + "%'");
            Vector v1 = new Vector();

            while (r.next()) {
                v1.add(r.getString("NIC"));

            }

            jComboBox5.setModel(new DefaultComboBoxModel(v1));
            jComboBox5.setPopupVisible(true);
            jTextField3.setText(jTextField3.getText());

        } catch (Exception e) {
            e.printStackTrace();

        }
    }//GEN-LAST:event_jTextField3KeyReleased

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        try {
            cls();
            int eno = 50001;
            String zx = null;
            int test = 0;
            Statement st = javaConnect.ConnectorDB();
            ResultSet rs = st.executeQuery("SELECT order_no FROM order_ref ORDER BY order_no");
            while (rs.next()) {
                zx = rs.getString("order_no");
                test = 1;
            }
            if (test == 1) {
                int a = Integer.parseInt(zx);
                a++;
                zx = Integer.toString(a);

            } else {
                zx = Integer.toString(eno);
            }
            jTextField1.setText(zx);

        } catch (Exception e) {

        }

        totOrder = 0;
        ino = 1;

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        String w = jTextField3.getText();
        Customer frame = new Customer(w);
        frame.setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        int dr = JOptionPane.showConfirmDialog(null, "Are You Sure You Want to Delete The Record?");
        if (dr == JOptionPane.YES_OPTION) {
            totOrder = 0;
            ino = 1;
            s1 = jTextField1.getText();
            String sql1 = "delete from order_items where order_no='" + s1 + "'";
            String sql2 = "delete from order_artwork where order_no='" + s1 + "'";
            String sql3 = "delete from order_payments where order_no='" + s1 + "'";
            String sql4 = "delete from order_ref where order_no='" + s1 + "'";

            try {
                Statement st = javaConnect.ConnectorDB();
                st.executeUpdate(sql4);
                st.executeUpdate(sql3);
                st.executeUpdate(sql2);
                st.executeUpdate(sql1);

            } catch (Exception e) {
            }

        }
        cls();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        cls();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTextField6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyTyped
        char c = evt.getKeyChar();

        if (Character.isDigit(c)) {

        } else {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField6KeyTyped

    private void jTextField6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyReleased

    }//GEN-LAST:event_jTextField6KeyReleased

    private void jTextField5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyReleased
        try {
            uprice = jTextField6.getText();
            s5 = jTextField5.getText();
            upriceint = Integer.parseInt(uprice);
            qty = Integer.parseInt(s5);

            int ppp = upriceint * qty;
            s4 = Integer.toString(ppp);
            jTextField4.setText(s4);

        } catch (Exception e) {
        }
    }//GEN-LAST:event_jTextField5KeyReleased

    private void jTextField5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyTyped
        char c = evt.getKeyChar();

        if (Character.isDigit(c)) {

        } else {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField5KeyTyped

    private void jTextField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyTyped
        char c = evt.getKeyChar();

        if (Character.isDigit(c)) {

        } else {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField4KeyTyped

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        s1 = jTextField1.getText();
        if (s1.equals("")) {
            Status sssss = new Status();
            sssss.setVisible(true);
        } else {
            Status sssss = new Status(s1);
            sssss.setVisible(true);
        }

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        String checkCno = jTextField1.getText();
        if (checkCno.equals("")) {

            Bill billwnindow = new Bill();
            billwnindow.setVisible(true);
        } else {
            System.out.println("111111111");
            Bill billwnindo = new Bill(checkCno);
            billwnindo.setVisible(true);
            System.out.println("2222222222222");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyTyped
        char c = evt.getKeyChar();

        if (Character.isDigit(c)) {
        } else {
            if (c == 'v' | c == 'V') {

            } else {
                evt.consume();
            }
        }
    }//GEN-LAST:event_jTextField3KeyTyped

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        char c = evt.getKeyChar();

        if (Character.isDigit(c)) {
        } else {
            evt.consume();
        }

    }//GEN-LAST:event_jTextField1KeyTyped

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        try {
            int dr = JOptionPane.showConfirmDialog(null, "Are You Sure You Want to Replace The Record?");
            if (dr == JOptionPane.YES_OPTION) {

                Statement st = javaConnect.ConnectorDB();
                st.executeUpdate("update order_ref set cust_nic='" + jTextField3.getText() + "' where order_no='" + jTextField1.getText() + "'");
                JOptionPane.showMessageDialog(null, "Customer ID Updated");

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }

    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed

        String gg = jTextField3.getText();
        if (gg.equalsIgnoreCase("")) {
            custOrder co = new custOrder();
            co.setVisible(true);
            this.dispose();
        } else {
            custOrder co = new custOrder(gg);
            co.setVisible(true);
            this.dispose();
        }

    }//GEN-LAST:event_jButton11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Order().setVisible(true);
            }
        });
    }

    public void getVal() {
        s1 = jTextField1.getText();
        //s2=jTextField2.getText();
        s3 = jTextField3.getText();
        s4 = jTextField4.getText();
        s5 = jTextField5.getText();
        // s6 = jTextField6.getText();

        sa2 = jTextArea2.getText();
        sa3 = jTextArea3.getText();

        Date d = new Date();
        ds1 = dt.format(jXDatePicker1.getDate());
        ds2day = dt.format(d);

        jcbs1 = (String) jComboBox1.getSelectedItem();
        jcbs2 = (String) jComboBox2.getSelectedItem();
        jcbs3 = (String) jComboBox3.getSelectedItem();
    }

    public void cls() {
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField6.setText("0");
        jTextField1.setText("");

        // jTextField9.setText("");
        DateFormat dt = new SimpleDateFormat("yyyy-MM-dd");

        String x = "2014-12-03";
        try {
            //Date y=dt.parse(x);
            // jXDatePicker1.setDate(y);
            Date d = new Date();
            dt.format(d);
            jXDatePicker1.setDate(d);

        } catch (Exception e) {
        }
        jTextArea2.setText("");
        jTextArea3.setText("");
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setNumRows(0);
        try {
            noImg();
        } catch (Exception e) {

        }

        totOrder = 0;
        ino = 1;

    }

    public void clsSameOrder() {
        //jTextField2.setText("");
        //jTextField3.setText("");
        jTextField4.setText("");
        jTextField6.setText("0");
        jTextField5.setText("0");
        //jTextField1.setText("");
        //jTextField6.setText("");
        // jTextField9.setText("");

        DateFormat dt = new SimpleDateFormat("yyyy-MM-dd");

        //String x = "2014-12-03";
        try {
            //Date y=dt.parse(x);
            // jXDatePicker1.setDate(y);
            Date d = new Date();
            dt.format(d);
            jXDatePicker1.setDate(d);

        } catch (Exception e) {
        }
        jTextArea2.setText("");
        jTextArea3.setText("");
        try {
            noImg();
        } catch (Exception e) {

        }

    }

    public void getLostImage() {
        try {
             format1 = new ImageIcon(getClass().getResource("/IMG/Lost.jpg"));
        } catch (Exception e) {
        }
    }

    public void noImg() {
        try {
            
            ImageIcon format = format1;
            jLabel8.setIcon(format);
            // pib=format.toString().getBytes();
            //pib=format.getClass().getResource("/IMG/Lost.jpg").getFile();

            File image = new File(getClass().getResource("/IMG/Lost.jpg").getFile());
            FileInputStream fis = new FileInputStream(image);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte[] buf = new byte[1024];

            for (int readNum; (readNum = fis.read(buf)) != -1;) {
                bos.write(buf, 0, readNum);
            }
            pib = bos.toByteArray();

        } catch (Exception e) {
            System.out.println("IMG error");
        }
    }

    public void lastItemNoCheck() throws Exception {
        Statement stt = javaConnect.ConnectorDB();
        ResultSet rss = stt.executeQuery("select item_no from order_items where order_no='" + s1 + "' ORDER BY item_no");

        String www = null;
        int test = 0;
        int a = 0;
        while (rss.next()) {
            www = rss.getString("item_no");
            test = 1;
        }
        if (test == 1) {
            a = Integer.parseInt(www);
            a++;
        }
        ino = a;

    }

    public void addItem() {
        getVal();
        try {
            Statement st = javaConnect.ConnectorDB();
            String sql1 = "select * from order_ref where order_no='" + s1 + "'";
            String sql2 = "select * from  order_payments where order_no='" + s1 + "'";
            ResultSet rs;
            rs = st.executeQuery(sql1);
            System.out.println("ok 1");
            if (rs.next()) {
                System.out.println("ok 1.1");
            } else {
                System.out.println("ok 2.1");
                inORef();

                System.out.println("ok 2");
            }
            rs = st.executeQuery(sql2);

            System.out.println("ok 3");
            if (rs.next()) {
                upOPay();
                System.out.println("ok 4");
            } else {
                System.out.println("ok 5");
                inOPay();
                System.out.println("ok 5.1");
            }
            try {
                inItem();

                try {
                    inArt();
                    ino = ino + 1;
                } catch (Exception e3) {
                    JOptionPane.showMessageDialog(this, e3);

                    delItem();
                    int ip = Integer.parseInt(s4);
                    totOrder = totOrder - ip;
                    ino = ino - 1;

                }
            } catch (Exception e2) {
                JOptionPane.showMessageDialog(this, e2);
                int ip = Integer.parseInt(s4);
                totOrder = totOrder - ip;

            }
        } catch (Exception e1) {
            System.out.println("EEEEEEEEEEEEEEEEEEEE");
        }

    }

    public void inORef() throws Exception {
        Connection conn;
        conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/final_project?zeroDateTimeBehavior=convertToNull", "root", "");
        String sqlref = "insert into order_ref values(?,?,?)";
        PreparedStatement pst = conn.prepareStatement(sqlref);
        pst.setString(1, s1);
        pst.setString(2, s3);
        pst.setString(3, ds2day);
        pst.execute();
        Statement st = javaConnect.ConnectorDB();
        String w = "NEW";
        st.executeUpdate("insert into order_status values('" + s1 + "','" + w + "')");
    }

    public void inItem() throws Exception {
        lastItemNoCheck();
        Connection conn;
        conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/final_project?zeroDateTimeBehavior=convertToNull", "root", "");
        String sqlitem = "insert into order_items values(?,?,?,?,?,?,?,?,?,?)";
        PreparedStatement pst = conn.prepareStatement(sqlitem);
        String xz = Integer.toString(ino);
        int ip = Integer.parseInt(s4);
        // totOrder = totOrder + ip;

        pst.setString(1, s1);
        pst.setString(2, xz);
        pst.setString(3, jcbs1);
        pst.setString(4, sa3);
        pst.setString(5, jcbs2);
        pst.setString(6, sa2);
        pst.setString(7, s5);
        pst.setString(8, jcbs3);
        pst.setString(9, s4);
        pst.setString(10, ds1);
        pst.execute();

    }

    public void inArt() throws Exception {
        Connection conn;
        conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/final_project?zeroDateTimeBehavior=convertToNull", "root", "");
        String sqlart = "insert into order_artwork values(?,?,?)";
        PreparedStatement pst = conn.prepareStatement(sqlart);
        String xz = Integer.toString(ino);
        pst.setString(1, s1);
        pst.setString(2, xz);
        pst.setBytes(3, pib);
        pst.execute();

    }

    public void inOPay() throws Exception {
        Connection conn;
        System.out.println("ok 6");
        totOrder = totOrder + Integer.parseInt(s4);
        s2 = Integer.toString(totOrder);
        conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/final_project?zeroDateTimeBehavior=convertToNull", "root", "");
        String sqlpay = "insert into order_payments values(?,?,?,?)";
        PreparedStatement pst = conn.prepareStatement(sqlpay);
        // String p = Integer.toString(totOrder);
        String x = "";
        pst.setString(1, s1);
        pst.setString(2, s2);
        pst.setString(3, x);
        pst.setString(4, x);
        System.out.println("ok 6.1");
        pst.execute();
        jTextField2.setText(s2);

    }

    public void delORef() {
        try {
            Statement st = javaConnect.ConnectorDB();
            String sql = "delete from order_ref where order_no='" + s1 + "' ";
            st.executeUpdate(sql);

        } catch (Exception e) {
        }

    }

    public void delItem() {
        try {
            String xz = Integer.toString(cino);
            Statement st = javaConnect.ConnectorDB();
            String sql = "delete from order_items where order_no='" + s1 + "' AND item_no='" + xz + "' ";
            st.executeUpdate(sql);

        } catch (Exception e) {
        }

    }

    public void delArt() {
        try {
            String xz = Integer.toString(cino);
            Statement st = javaConnect.ConnectorDB();
            String sql = "delete from  order_artwork where order_no='" + s1 + "' AND item_no='" + xz + "' ";
            st.executeUpdate(sql);

        } catch (Exception e) {
        }

    }

    public void delOPay() {
        try {
            Statement st = javaConnect.ConnectorDB();
            String sql = "delete from order_payments where order_no='" + s1 + "' ";
            st.executeUpdate(sql);

        } catch (Exception e) {
        }

    }

    public void upOPay() {
        try {
            //s2=jTextField2.getText();
            totOrder = totOrder + Integer.parseInt(s4);
            s2 = Integer.toString(totOrder);
            jTextField2.setText(s2);
            Statement st = javaConnect.ConnectorDB();
            String sql = "update order_payments set total='" + s2 + "' where order_no='" + s1 + "' ";
            st.executeUpdate(sql);

        } catch (Exception e) {
        }

    }

    public void searchByOrder() {
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setNumRows(0);

        try {
            String OrNo = jTextField1.getText();
            String a = "";

            Statement st = javaConnect.ConnectorDB();
            String sql1 = "select * from order_ref where order_no='" + OrNo + "' ";
            String sql2 = "select * from order_items where order_no='" + OrNo + "' ";
            String sql3 = "select total from order_payments where order_no='" + OrNo + "' ";

            ResultSet rs = st.executeQuery(sql1);
            if (rs.next()) {
                s3 = rs.getString("cust_nic");
                ds2day = rs.getString("o_date");
            }
            rs = st.executeQuery(sql2);
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

            while (rs.next()) {
                s1 = rs.getString("order_no");
                a = rs.getString("item_no");
                jcbs1 = rs.getString("type");
                sa3 = rs.getString("desc");
                jcbs2 = rs.getString("no_colours");
                sa2 = rs.getString("colours");
                s5 = rs.getString("size");
                jcbs3 = rs.getString("screen");
                s4 = rs.getString("item_price");
                ds1 = rs.getString("finish_date");

                Object[] row = {s1, s3, a, jcbs1, sa3, jcbs2, sa2, s5, jcbs3, s4, ds2day, ds1};
                model.addRow(row);
            }
            totOrder = Integer.parseInt(s2);
            ino = Integer.parseInt(a);
            rs = st.executeQuery(sql3);
            if (rs.next()) {
                s2 = rs.getString("total");
                totOrder = Integer.parseInt(s2);

            }
        } catch (Exception e) {
        }

        jTextField3.setText(s3);
        jTextField2.setText(s2);
        clsSameOrder();

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private com.toedter.calendar.JDateChooser jXDatePicker1;
    // End of variables declaration//GEN-END:variables

    private ImageIcon format = null;
    private ImageIcon format1 = null;
    String filename = null;
    int s = 0;
    byte[] pib = null;
    String s2 = "0";
    String s3 = null;
    String s4 = null;
    String s5 = null;
    String s1 = null;
    String s6 = "0";
    String sa3 = null;
    String sa2 = null;

    String uprice = "0";
    int upriceint = 0;

    String jcbs1 = null;
    String jcbs2 = null;
    String jcbs3 = null;

    String ds1 = null;
    String ds2day = null;
    DateFormat dt = new SimpleDateFormat("yyyy-MM-dd");
    int qty = 0;
    int ino = 1;
    int cino = 0;
    int totOrder = 0;
    int ipval = 0;
}
